// data for referencing countries and regions
// functions for displaying countries and regions on lists / dropdowns etc.
var all_countries_world_bank = {
    "Aruba":["ABW","Latin America & Caribbean"],
    "Afghanistan":["AFG","South Asia"],
    "Angola":["AGO","Sub-Saharan Africa"],
    "Albania":["ALB","Europe & Central Asia"],
    "Andorra":["AND","Europe & Central Asia"],
    "United Arab Emirates":["ARE","Middle East & North Africa"],
    "Argentina":["ARG","Latin America & Caribbean"],
    "Armenia":["ARM","Europe & Central Asia"],
    "American Samoa":["ASM","East Asia & Pacific"],
    "Antigua and Barbuda":["ATG","Latin America & Caribbean"],
    "Australia":["AUS","East Asia & Pacific"],
    "Austria":["AUT","Europe & Central Asia"],
    "Azerbaijan":["AZE","Europe & Central Asia"],
    "Burundi":["BDI","Sub-Saharan Africa"],
    "Belgium":["BEL","Europe & Central Asia"],
    "Benin":["BEN","Sub-Saharan Africa"],
    "Burkina Faso":["BFA","Sub-Saharan Africa"],
    "Bangladesh":["BGD","South Asia"],
    "Bulgaria":["BGR","Europe & Central Asia"],
    "Bahrain":["BHR","Middle East & North Africa"],
    "Bahamas, The":["BHS","Latin America & Caribbean"],
    "Bosnia and Herzegovina":["BIH","Europe & Central Asia"],
    "Belarus":["BLR","Europe & Central Asia"],
    "Belize":["BLZ","Latin America & Caribbean"],
    "Bermuda":["BMU","North America"],
    "Bolivia":["BOL","Latin America & Caribbean"],
    "Brazil":["BRA","Latin America & Caribbean"],
    "Barbados":["BRB","Latin America & Caribbean"],
    "Brunei Darussalam":["BRN","East Asia & Pacific"],
    "Bhutan":["BTN","South Asia"],
    "Botswana":["BWA","Sub-Saharan Africa"],
    "Central African Republic":["CAF","Sub-Saharan Africa"],
    "Canada":["CAN","North America"],
    "Switzerland":["CHE","Europe & Central Asia"],
    "Channel Islands":["CHI","Europe & Central Asia"],
    "Chile":["CHL","Latin America & Caribbean"],
    "China":["CHN","East Asia & Pacific"],
    "Cote d'Ivoire":["CIV","Sub-Saharan Africa"],
    "Cameroon":["CMR","Sub-Saharan Africa"],
    "Congo, Dem. Rep.":["COD","Sub-Saharan Africa"],
    "Congo, Rep.":["COG","Sub-Saharan Africa"],
    "Colombia":["COL","Latin America & Caribbean"],
    "Comoros":["COM","Sub-Saharan Africa"],
    "Cabo Verde":["CPV","Sub-Saharan Africa"],
    "Costa Rica":["CRI","Latin America & Caribbean"],
    "Cuba":["CUB","Latin America & Caribbean"],
    "Curacao":["CUW","Latin America & Caribbean"],
    "Cayman Islands":["CYM","Latin America & Caribbean"],
    "Cyprus":["CYP","Europe & Central Asia"],
    "Czech Republic":["CZE","Europe & Central Asia"],
    "Germany":["DEU","Europe & Central Asia"],
    "Djibouti":["DJI","Middle East & North Africa"],
    "Dominica":["DMA","Latin America & Caribbean"],
    "Denmark":["DNK","Europe & Central Asia"],
    "Dominican Republic":["DOM","Latin America & Caribbean"],
    "Algeria":["DZA","Middle East & North Africa"],
    "Ecuador":["ECU","Latin America & Caribbean"],
    "Egypt, Arab Rep.":["EGY","Middle East & North Africa"],
    "Eritrea":["ERI","Sub-Saharan Africa"],
    "Spain":["ESP","Europe & Central Asia"],
    "Estonia":["EST","Europe & Central Asia"],
    "Ethiopia":["ETH","Sub-Saharan Africa"],
    "Finland":["FIN","Europe & Central Asia"],
    "Fiji":["FJI","East Asia & Pacific"],
    "France":["FRA","Europe & Central Asia"],
    "Faroe Islands":["FRO","Europe & Central Asia"],
    "Micronesia, Fed. Sts.":["FSM","East Asia & Pacific"],
    "Gabon":["GAB","Sub-Saharan Africa"],
    "United Kingdom":["GBR","Europe & Central Asia"],
    "Georgia":["GEO","Europe & Central Asia"],
    "Ghana":["GHA","Sub-Saharan Africa"],
    "Gibraltar":["GIB","Europe & Central Asia"],
    "Guinea":["GIN","Sub-Saharan Africa"],
    "Gambia, The":["GMB","Sub-Saharan Africa"],
    "Guinea-Bissau":["GNB","Sub-Saharan Africa"],
    "Equatorial Guinea":["GNQ","Sub-Saharan Africa"],
    "Greece":["GRC","Europe & Central Asia"],
    "Grenada":["GRD","Latin America & Caribbean"],
    "Greenland":["GRL","Europe & Central Asia"],
    "Guatemala":["GTM","Latin America & Caribbean"],
    "Guam":["GUM","East Asia & Pacific"],
    "Guyana":["GUY","Latin America & Caribbean"],
    "Hong Kong SAR, China":["HKG","East Asia & Pacific"],
    "Honduras":["HND","Latin America & Caribbean"],
    "Croatia":["HRV","Europe & Central Asia"],
    "Haiti":["HTI","Latin America & Caribbean"],
    "Hungary":["HUN","Europe & Central Asia"],
    "Indonesia":["IDN","East Asia & Pacific"],
    "Isle of Man":["IMN","Europe & Central Asia"],
    "India":["IND","South Asia"],
    "Ireland":["IRL","Europe & Central Asia"],
    "Iran, Islamic Rep.":["IRN","Middle East & North Africa"],
    "Iraq":["IRQ","Middle East & North Africa"],
    "Iceland":["ISL","Europe & Central Asia"],
    "Israel":["ISR","Middle East & North Africa"],
    "Italy":["ITA","Europe & Central Asia"],
    "Jamaica":["JAM","Latin America & Caribbean"],
    "Jordan":["JOR","Middle East & North Africa"],
    "Japan":["JPN","East Asia & Pacific"],
    "Kazakhstan":["KAZ","Europe & Central Asia"],
    "Kenya":["KEN","Sub-Saharan Africa"],
    "Kyrgyz Republic":["KGZ","Europe & Central Asia"],
    "Cambodia":["KHM","East Asia & Pacific"],
    "Kiribati":["KIR","East Asia & Pacific"],
    "St. Kitts and Nevis":["KNA","Latin America & Caribbean"],
    "Korea, Rep.":["KOR","East Asia & Pacific"],
    "Kuwait":["KWT","Middle East & North Africa"],
    "Lao PDR":["LAO","East Asia & Pacific"],
    "Lebanon":["LBN","Middle East & North Africa"],
    "Liberia":["LBR","Sub-Saharan Africa"],
    "Libya":["LBY","Middle East & North Africa"],
    "St. Lucia":["LCA","Latin America & Caribbean"],
    "Liechtenstein":["LIE","Europe & Central Asia"],
    "Sri Lanka":["LKA","South Asia"],
    "Lesotho":["LSO","Sub-Saharan Africa"],
    "Lithuania":["LTU","Europe & Central Asia"],
    "Luxembourg":["LUX","Europe & Central Asia"],
    "Latvia":["LVA","Europe & Central Asia"],
    "Macao SAR, China":["MAC","East Asia & Pacific"],
    "St. Martin (French part)":["MAF","Latin America & Caribbean"],
    "Morocco":["MAR","Middle East & North Africa"],
    "Monaco":["MCO","Europe & Central Asia"],
    "Moldova":["MDA","Europe & Central Asia"],
    "Madagascar":["MDG","Sub-Saharan Africa"],
    "Maldives":["MDV","South Asia"],
    "Mexico":["MEX","Latin America & Caribbean"],
    "Marshall Islands":["MHL","East Asia & Pacific"],
    "North Macedonia":["MKD","Europe & Central Asia"],
    "Mali":["MLI","Sub-Saharan Africa"],
    "Malta":["MLT","Middle East & North Africa"],
    "Myanmar":["MMR","East Asia & Pacific"],
    "Montenegro":["MNE","Europe & Central Asia"],
    "Mongolia":["MNG","East Asia & Pacific"],
    "Northern Mariana Islands":["MNP","East Asia & Pacific"],
    "Mozambique":["MOZ","Sub-Saharan Africa"],
    "Mauritania":["MRT","Sub-Saharan Africa"],
    "Mauritius":["MUS","Sub-Saharan Africa"],
    "Malawi":["MWI","Sub-Saharan Africa"],
    "Malaysia":["MYS","East Asia & Pacific"],
    "Namibia":["NAM","Sub-Saharan Africa"],
    "New Caledonia":["NCL","East Asia & Pacific"],
    "Niger":["NER","Sub-Saharan Africa"],
    "Nigeria":["NGA","Sub-Saharan Africa"],
    "Nicaragua":["NIC","Latin America & Caribbean"],
    "Netherlands":["NLD","Europe & Central Asia"],
    "Norway":["NOR","Europe & Central Asia"],
    "Nepal":["NPL","South Asia"],
    "Nauru":["NRU","East Asia & Pacific"],
    "New Zealand":["NZL","East Asia & Pacific"],
    "Oman":["OMN","Middle East & North Africa"],
    "Pakistan":["PAK","South Asia"],
    "Panama":["PAN","Latin America & Caribbean"],
    "Peru":["PER","Latin America & Caribbean"],
    "Philippines":["PHL","East Asia & Pacific"],
    "Palau":["PLW","East Asia & Pacific"],
    "Papua New Guinea":["PNG","East Asia & Pacific"],
    "Poland":["POL","Europe & Central Asia"],
    "Puerto Rico":["PRI","Latin America & Caribbean"],
    "Korea, Dem. People's Rep.":["PRK","East Asia & Pacific"],
    "Portugal":["PRT","Europe & Central Asia"],
    "Paraguay":["PRY","Latin America & Caribbean"],
    "West Bank and Gaza":["PSE","Middle East & North Africa"],
    "French Polynesia":["PYF","East Asia & Pacific"],
    "Qatar":["QAT","Middle East & North Africa"],
    "Romania":["ROU","Europe & Central Asia"],
    "Russian Federation":["RUS","Europe & Central Asia"],
    "Rwanda":["RWA","Sub-Saharan Africa"],
    "Saudi Arabia":["SAU","Middle East & North Africa"],
    "Sudan":["SDN","Sub-Saharan Africa"],
    "Senegal":["SEN","Sub-Saharan Africa"],
    "Singapore":["SGP","East Asia & Pacific"],
    "Solomon Islands":["SLB","East Asia & Pacific"],
    "Sierra Leone":["SLE","Sub-Saharan Africa"],
    "El Salvador":["SLV","Latin America & Caribbean"],
    "San Marino":["SMR","Europe & Central Asia"],
    "Somalia":["SOM","Sub-Saharan Africa"],
    "Serbia":["SRB","Europe & Central Asia"],
    "South Sudan":["SSD","Sub-Saharan Africa"],
    "Sao Tome and Principe":["STP","Sub-Saharan Africa"],
    "Suriname":["SUR","Latin America & Caribbean"],
    "Slovak Republic":["SVK","Europe & Central Asia"],
    "Slovenia":["SVN","Europe & Central Asia"],
    "Sweden":["SWE","Europe & Central Asia"],
    "Eswatini":["SWZ","Sub-Saharan Africa"],
    "Sint Maarten (Dutch part)":["SXM","Latin America & Caribbean"],
    "Seychelles":["SYC","Sub-Saharan Africa"],
    "Syrian Arab Republic":["SYR","Middle East & North Africa"],
    "Turks and Caicos Islands":["TCA","Latin America & Caribbean"],
    "Chad":["TCD","Sub-Saharan Africa"],
    "Togo":["TGO","Sub-Saharan Africa"],
    "Thailand":["THA","East Asia & Pacific"],
    "Tajikistan":["TJK","Europe & Central Asia"],
    "Turkmenistan":["TKM","Europe & Central Asia"],
    "Timor-Leste":["TLS","East Asia & Pacific"],
    "Tonga":["TON","East Asia & Pacific"],
    "Trinidad and Tobago":["TTO","Latin America & Caribbean"],
    "Tunisia":["TUN","Middle East & North Africa"],
    "Turkey":["TUR","Europe & Central Asia"],
    "Tuvalu":["TUV","East Asia & Pacific"],
    "Tanzania":["TZA","Sub-Saharan Africa"],
    "Uganda":["UGA","Sub-Saharan Africa"],
    "Ukraine":["UKR","Europe & Central Asia"],
    "Uruguay":["URY","Latin America & Caribbean"],
    "United States":["USA","North America"],
    "Uzbekistan":["UZB","Europe & Central Asia"],
    "St. Vincent and the Grenadines":["VCT","Latin America & Caribbean"],
    "Venezuela, RB":["VEN","Latin America & Caribbean"],
    "British Virgin Islands":["VGB","Latin America & Caribbean"],
    "Virgin Islands (U.S.)":["VIR","Latin America & Caribbean"],
    "Vietnam":["VNM","East Asia & Pacific"],
    "Vanuatu":["VUT","East Asia & Pacific"],
    "Samoa":["WSM","East Asia & Pacific"],
    "Kosovo":["XKX","Europe & Central Asia"],
    "Yemen, Rep.":["YEM","Middle East & North Africa"],
    "South Africa":["ZAF","Sub-Saharan Africa"],
    "Zambia":["ZMB","Sub-Saharan Africa"],
    "Zimbabwe":["ZWE","Sub-Saharan Africa"]
};

var all_countries_sdg = {
    "Afghanistan":["AFG","Central and Southern Asia"],
    "Åland Islands":["ALA","Europe"],
    "Albania":["ALB","Europe"],
    "Algeria":["DZA","Northern Africa and Western Asia"],
    "American Samoa":["ASM","Oceania"],
    "Andorra":["AND","Europe"],
    "Angola":["AGO","Sub-Saharan Africa"],
    "Anguilla":["AIA","Latin America and the Caribbean"],
    "Antigua and Barbuda":["ATG","Latin America and the Caribbean"],
    "Argentina":["ARG","Latin America and the Caribbean"],
    "Armenia":["ARM","Northern Africa and Western Asia"],
    "Aruba":["ABW","Latin America and the Caribbean"],
    "Australia":["AUS","Australia and New Zealand"],
    "Austria":["AUT","Europe"],
    "Azerbaijan":["AZE","Northern Africa and Western Asia"],
    "Bahamas":["BHS","Latin America and the Caribbean"],
    "Bahrain":["BHR","Northern Africa and Western Asia"],
    "Bangladesh":["BGD","Central and Southern Asia"],
    "Barbados":["BRB","Latin America and the Caribbean"],
    "Belarus":["BLR","Europe"],
    "Belgium":["BEL","Europe"],
    "Belize":["BLZ","Latin America and the Caribbean"],
    "Benin":["BEN","Sub-Saharan Africa"],
    "Bermuda":["BMU","North America"],
    "Bhutan":["BTN","Central and Southern Asia"],
    "Bolivia":["BOL","Latin America and the Caribbean"],
    "Bonaire, Sint Eustatius and Saba":["BES","Latin America and the Caribbean"],
    "Bosnia and Herzegovina":["BIH","Europe"],
    "Botswana":["BWA","Sub-Saharan Africa"],
    "Bouvet Island":["BVT","Latin America and the Caribbean"],
    "Brazil":["BRA","Latin America and the Caribbean"],
    "British Indian Ocean Territory":["IOT","Sub-Saharan Africa"],
    "British Virgin Islands":["VGB","Latin America and the Caribbean"],
    "Brunei Darussalam":["BRN","Eastern and South-Eastern Asia"],
    "Bulgaria":["BGR","Europe"],
    "Burkina Faso":["BFA","Sub-Saharan Africa"],
    "Burundi":["BDI","Sub-Saharan Africa"],
    "Cabo Verde":["CPV","Sub-Saharan Africa"],
    "Cambodia":["KHM","Eastern and South-Eastern Asia"],
    "Cameroon":["CMR","Sub-Saharan Africa"],
    "Canada":["CAN","North America"],
    "Cayman Islands":["CYM","Latin America and the Caribbean"],
    "Central African Republic":["CAF","Sub-Saharan Africa"],
    "Chad":["TCD","Sub-Saharan Africa"],
    "Chile":["CHL","Latin America and the Caribbean"],
    "China":["CHN","Eastern and South-Eastern Asia"],
    "Christmas Island":["CXR","Australia and New Zealand"],
    "Cocos (Keeling) Islands":["CCK","Australia and New Zealand"],
    "Colombia":["COL","Latin America and the Caribbean"],
    "Comoros":["COM","Sub-Saharan Africa"],
    "Congo":["COG","Sub-Saharan Africa"],
    "Cook Islands":["COK","Oceania"],
    "Costa Rica":["CRI","Latin America and the Caribbean"],
    "Côte d’Ivoire":["CIV","Sub-Saharan Africa"],
    "Croatia":["HRV","Europe"],
    "Cuba":["CUB","Latin America and the Caribbean"],
    "Curaçao":["CUW","Latin America and the Caribbean"],
    "Cyprus":["CYP","Northern Africa and Western Asia"],
    "Czechia":["CZE","Europe"],
    "Democratic Republic of the Congo":["COD","Sub-Saharan Africa"],
    "Denmark":["DNK","Europe"],
    "Djibouti":["DJI","Sub-Saharan Africa"],
    "Dominica":["DMA","Latin America and the Caribbean"],
    "Dominican Republic":["DOM","Latin America and the Caribbean"],
    "Ecuador":["ECU","Latin America and the Caribbean"],
    "Egypt":["EGY","Northern Africa and Western Asia"],
    "El Salvador":["SLV","Latin America and the Caribbean"],
    "Equatorial Guinea":["GNQ","Sub-Saharan Africa"],
    "Eritrea":["ERI","Sub-Saharan Africa"],
    "Estonia":["EST","Europe"],
    "Ethiopia":["ETH","Sub-Saharan Africa"],
    "Falkland Islands":["FLK","Latin America and the Caribbean"],
    "Faroe Islands":["FRO","Europe"],
    "Fiji":["FJI","Oceania"],
    "Finland":["FIN","Europe"],
    "France":["FRA","Europe"],
    "French Guiana":["GUF","Latin America and the Caribbean"],
    "French Polynesia":["PYF","Oceania"],
    "French Southern Territories":["ATF","Sub-Saharan Africa"],
    "Gabon":["GAB","Sub-Saharan Africa"],
    "Gambia":["GMB","Sub-Saharan Africa"],
    "Georgia":["GEO","Northern Africa and Western Asia"],
    "Germany":["DEU","Europe"],
    "Ghana":["GHA","Sub-Saharan Africa"],
    "Gibraltar":["GIB","Europe"],
    "Greece":["GRC","Europe"],
    "Greenland":["GRL","North America"],
    "Grenada":["GRD","Latin America and the Caribbean"],
    "Guadeloupe":["GLP","Latin America and the Caribbean"],
    "Guam":["GUM","Oceania"],
    "Guatemala":["GTM","Latin America and the Caribbean"],
    "Guernsey":["GGY","Europe"],
    "Guinea":["GIN","Sub-Saharan Africa"],
    "Guinea-Bissau":["GNB","Sub-Saharan Africa"],
    "Guyana":["GUY","Latin America and the Caribbean"],
    "Haiti":["HTI","Latin America and the Caribbean"],
    "Heard Island and McDonald Islands":["HMD","Australia and New Zealand"],
    "Holy See":["VAT","Europe"],
    "Honduras":["HND","Latin America and the Caribbean"],
    "Hong Kong":["HKG","Eastern and South-Eastern Asia"],
    "Hungary":["HUN","Europe"],
    "Iceland":["ISL","Europe"],
    "India":["IND","Central and Southern Asia"],
    "Indonesia":["IDN","Eastern and South-Eastern Asia"],
    "Iran":["IRN","Central and Southern Asia"],
    "Iraq":["IRQ","Northern Africa and Western Asia"],
    "Ireland":["IRL","Europe"],
    "Isle of Man":["IMN","Europe"],
    "Israel":["ISR","Northern Africa and Western Asia"],
    "Italy":["ITA","Europe"],
    "Jamaica":["JAM","Latin America and the Caribbean"],
    "Japan":["JPN","Eastern and South-Eastern Asia"],
    "Jersey":["JEY","Europe"],
    "Jordan":["JOR","Northern Africa and Western Asia"],
    "Kazakhstan":["KAZ","Central and Southern Asia"],
    "Kenya":["KEN","Sub-Saharan Africa"],
    "Kiribati":["KIR","Oceania"],
    "Kuwait":["KWT","Northern Africa and Western Asia"],
    "Kyrgyzstan":["KGZ","Central and Southern Asia"],
    "Lao":["LAO","Eastern and South-Eastern Asia"],
    "Latvia":["LVA","Europe"],
    "Lebanon":["LBN","Northern Africa and Western Asia"],
    "Lesotho":["LSO","Sub-Saharan Africa"],
    "Liberia":["LBR","Sub-Saharan Africa"],
    "Libya":["LBY","Northern Africa and Western Asia"],
    "Liechtenstein":["LIE","Europe"],
    "Lithuania":["LTU","Europe"],
    "Luxembourg":["LUX","Europe"],
    "Macao":["MAC","Eastern and South-Eastern Asia"],
    "Madagascar":["MDG","Sub-Saharan Africa"],
    "Malawi":["MWI","Sub-Saharan Africa"],
    "Malaysia":["MYS","Eastern and South-Eastern Asia"],
    "Maldives":["MDV","Central and Southern Asia"],
    "Mali":["MLI","Sub-Saharan Africa"],
    "Malta":["MLT","Europe"],
    "Marshall Islands":["MHL","Oceania"],
    "Martinique":["MTQ","Latin America and the Caribbean"],
    "Mauritania":["MRT","Sub-Saharan Africa"],
    "Mauritius":["MUS","Sub-Saharan Africa"],
    "Mayotte":["MYT","Sub-Saharan Africa"],
    "Mexico":["MEX","Latin America and the Caribbean"],
    "Micronesia":["FSM","Oceania"],
    "Moldova":["MDA","Europe"],
    "Monaco":["MCO","Europe"],
    "Mongolia":["MNG","Eastern and South-Eastern Asia"],
    "Montenegro":["MNE","Europe"],
    "Montserrat":["MSR","Latin America and the Caribbean"],
    "Morocco":["MAR","Northern Africa and Western Asia"],
    "Mozambique":["MOZ","Sub-Saharan Africa"],
    "Myanmar":["MMR","Eastern and South-Eastern Asia"],
    "Namibia":["NAM","Sub-Saharan Africa"],
    "Nauru":["NRU","Oceania"],
    "Nepal":["NPL","Central and Southern Asia"],
    "Netherlands":["NLD","Europe"],
    "New Caledonia":["NCL","Oceania"],
    "New Zealand":["NZL","Australia and New Zealand"],
    "Nicaragua":["NIC","Latin America and the Caribbean"],
    "Niger":["NER","Sub-Saharan Africa"],
    "Nigeria":["NGA","Sub-Saharan Africa"],
    "Niue":["NIU","Oceania"],
    "Norfolk Island":["NFK","Australia and New Zealand"],
    "North Korea":["PRK","Eastern and South-Eastern Asia"],
    "North Macedonia":["MKD","Europe"],
    "Northern Mariana Islands":["MNP","Oceania"],
    "Norway":["NOR","Europe"],
    "Oman":["OMN","Northern Africa and Western Asia"],
    "Pakistan":["PAK","Central and Southern Asia"],
    "Palau":["PLW","Oceania"],
    "Panama":["PAN","Latin America and the Caribbean"],
    "Papua New Guinea":["PNG","Oceania"],
    "Paraguay":["PRY","Latin America and the Caribbean"],
    "Peru":["PER","Latin America and the Caribbean"],
    "Philippines":["PHL","Eastern and South-Eastern Asia"],
    "Pitcairn":["PCN","Oceania"],
    "Poland":["POL","Europe"],
    "Portugal":["PRT","Europe"],
    "Puerto Rico":["PRI","Latin America and the Caribbean"],
    "Qatar":["QAT","Northern Africa and Western Asia"],
    "Réunion":["REU","Sub-Saharan Africa"],
    "Romania":["ROU","Europe"],
    "Russia":["RUS","Europe"],
    "Rwanda":["RWA","Sub-Saharan Africa"],
    "Saint Barthélemy":["BLM","Latin America and the Caribbean"],
    "Saint Helena":["SHN","Sub-Saharan Africa"],
    "Saint Kitts and Nevis":["KNA","Latin America and the Caribbean"],
    "Saint Lucia":["LCA","Latin America and the Caribbean"],
    "Saint Martin (French Part)":["MAF","Latin America and the Caribbean"],
    "Saint Pierre and Miquelon":["SPM","North America"],
    "Saint Vincent and the Grenadines":["VCT","Latin America and the Caribbean"],
    "Samoa":["WSM","Oceania"],
    "San Marino":["SMR","Europe"],
    "Sao Tome and Principe":["STP","Sub-Saharan Africa"],
    "Sark":["SAR","Europe"],
    "Saudi Arabia":["SAU","Northern Africa and Western Asia"],
    "Senegal":["SEN","Sub-Saharan Africa"],
    "Serbia":["SRB","Europe"],
    "Seychelles":["SYC","Sub-Saharan Africa"],
    "Sierra Leone":["SLE","Sub-Saharan Africa"],
    "Singapore":["SGP","Eastern and South-Eastern Asia"],
    "Sint Maarten (Dutch part)":["SXM","Latin America and the Caribbean"],
    "Slovakia":["SVK","Europe"],
    "Slovenia":["SVN","Europe"],
    "Solomon Islands":["SLB","Oceania"],
    "Somalia":["SOM","Sub-Saharan Africa"],
    "South Africa":["ZAF","Sub-Saharan Africa"],
    "South Georgia and the South Sandwich Islands":["SGS","Latin America and the Caribbean"],
    "South Korea":["KOR","Eastern and South-Eastern Asia"],
    "South Sudan":["SSD","Sub-Saharan Africa"],
    "Spain":["ESP","Europe"],
    "Sri Lanka":["LKA","Central and Southern Asia"],
    "State of Palestine":["PSE","Northern Africa and Western Asia"],
    "Sudan":["SDN","Northern Africa and Western Asia"],
    "Suriname":["SUR","Latin America and the Caribbean"],
    "Svalbard and Jan Mayen Islands":["SJM","Europe"],
    "Swaziland":["SWZ","Sub-Saharan Africa"],
    "Sweden":["SWE","Europe"],
    "Switzerland":["CHE","Europe"],
    "Syria":["SYR","Northern Africa and Western Asia"],
    "Tajikistan":["TJK","Central and Southern Asia"],
    "Tanzania":["TZA","Sub-Saharan Africa"],
    "Thailand":["THA","Eastern and South-Eastern Asia"],
    "Timor-Leste":["TLS","Eastern and South-Eastern Asia"],
    "Togo":["TGO","Sub-Saharan Africa"],
    "Tokelau":["TKL","Oceania"],
    "Tonga":["TON","Oceania"],
    "Trinidad and Tobago":["TTO","Latin America and the Caribbean"],
    "Tunisia":["TUN","Northern Africa and Western Asia"],
    "Turkey":["TUR","Northern Africa and Western Asia"],
    "Turkmenistan":["TKM","Central and Southern Asia"],
    "Turks and Caicos Islands":["TCA","Latin America and the Caribbean"],
    "Tuvalu":["TUV","Oceania"],
    "Uganda":["UGA","Sub-Saharan Africa"],
    "Ukraine":["UKR","Europe"],
    "United Arab Emirates":["ARE","Northern Africa and Western Asia"],
    "United Kingdom":["GBR","Europe"],
    "United States Minor Outlying Islands":["UMI","Oceania"],
    "United States of America":["USA","North America"],
    "United States Virgin Islands":["VIR","Latin America and the Caribbean"],
    "Uruguay":["URY","Latin America and the Caribbean"],
    "Uzbekistan":["UZB","Central and Southern Asia"],
    "Vanuatu":["VUT","Oceania"],
    "Venezuela":["VEN","Latin America and the Caribbean"],
    "Vietnam":["VNM","Eastern and South-Eastern Asia"],
    "Wallis and Futuna Islands":["WLF","Oceania"],
    "Western Sahara":["ESH","Northern Africa and Western Asia"],
    "Yemen":["YEM","Northern Africa and Western Asia"],
    "Zambia":["ZMB","Sub-Saharan Africa"],
    "Zimbabwe":["ZWE","Sub-Saharan Africa"]
};
var all_regions_sdg = {
    "Australia and New Zealand":[
        "Australia",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Heard Island and McDonald Islands",
        "New Zealand",
        "Norfolk Island"],
    "Central and Southern Asia":[
        "Afghanistan",
        "Bangladesh",
        "Bhutan",
        "India",
        "Iran",
        "Kazakhstan",
        "Kyrgyzstan",
        "Maldives",
        "Nepal",
        "Pakistan",
        "Sri Lanka",
        "Tajikistan",
        "Turkmenistan",
        "Uzbekistan"],
    "Eastern and South-Eastern Asia":[
        "Brunei Darussalam",
        "Cambodia",
        "China",
        "Hong Kong",
        "Indonesia",
        "Japan",
        "Lao",
        "Macao",
        "Malaysia",
        "Mongolia",
        "Myanmar",
        "North Korea",
        "Philippines",
        "Singapore",
        "South Korea",
        "Thailand",
        "Timor-Leste",
        "Vietnam"],
    "Europe":[
        "Aland Islands",
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Czechia",
        "Denmark",
        "Estonia",
        "Faroe Islands",
        "Finland",
        "France",
        "Germany",
        "Gibraltar",
        "Greece",
        "Guernsey",
        "Holy See",
        "Hungary",
        "Iceland",
        "Ireland",
        "Isle of Man",
        "Italy",
        "Jersey",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "North Macedonia",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "San Marino",
        "Sark",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Svalbard and Jan Mayen Islands",
        "Sweden",
        "Switzerland",
        "Ukraine",
        "United Kingdom"],
    "Latin America and the Caribbean":[
        "Anguilla",
        "Antigua and Barbuda",
        "Argentina",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bolivia",
        "Bonaire, Sint Eustatius and Saba",
        "Bouvet Island",
        "Brazil",
        "British Virgin Islands",
        "Cayman Islands",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Curaçao",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "El Salvador",
        "Falkland Islands",
        "French Guiana",
        "Grenada",
        "Guadeloupe",
        "Guatemala",
        "Guyana",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Martinique",
        "Mexico",
        "Montserrat",
        "Nicaragua",
        "Panama",
        "Paraguay",
        "Peru",
        "Puerto Rico",
        "Saint Barthélemy",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin (French Part)",
        "Saint Vincent and the Grenadines",
        "Sint Maarten (Dutch part)",
        "South Georgia and the South Sandwich Islands",
        "Suriname",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "United States Virgin Islands",
        "Uruguay",
        "Venezuela"],
    "Northern Africa and Western Asia":[
        "Algeria",
        "Armenia",
        "Azerbaijan",
        "Bahrain",
        "Cyprus",
        "Egypt",
        "Georgia",
        "Iraq",
        "Israel",
        "Jordan",
        "Kuwait",
        "Lebanon",
        "Libya",
        "Morocco",
        "Oman",
        "Qatar",
        "Saudi Arabia",
        "State of Palestine",
        "Sudan",
        "Syria",
        "Tunisia",
        "Turkey",
        "United Arab Emirates",
        "Western Sahara",
        "Yemen"],
    "North America":[
        "Bermuda",
        "Canada",
        "Greenland",
        "Saint Pierre and Miquelon",
        "United States of America"],
    "Oceania":[
        "American Samoa",
        "Cook Islands",
        "Fiji",
        "French Polynesia",
        "Guam",
        "Kiribati",
        "Marshall Islands",
        "Micronesia",
        "Nauru",
        "New Caledonia",
        "Niue",
        "Northern Mariana Islands",
        "Palau",
        "Papua New Guinea",
        "Pitcairn",
        "Samoa",
        "Solomon Islands",
        "Tokelau",
        "Tonga",
        "Tuvalu",
        "United States Minor Outlying Islands",
        "Vanuatu",
        "Wallis and Futuna Islands"],
    "Sub-Saharan Africa":[
        "Angola",
        "Benin",
        "Botswana",
        "British Indian Ocean Territory",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cameroon",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo",
        "Côte d’Ivoire",
        "Democratic Republic of the Congo",
        "Djibouti",
        "Equatorial Guinea",
        "Eritrea",
        "Ethiopia",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Réunion",
        "Rwanda",
        "Saint Helena",
        "Sao Tome and Principe",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Swaziland",
        "Tanzania",
        "Togo",
        "Uganda",
        "Zambia",
        "Zimbabwe"]
};
var all_regions_world_bank ={
    "East Asia & Pacific":[
        "American Samoa",
        "Australia",
        "Brunei Darussalam",
        "China",
        "Fiji",
        "Micronesia, Fed. Sts.",
        "Guam",
        "Hong Kong SAR, China",
        "Indonesia",
        "Japan",
        "Cambodia",
        "Kiribati",
        "Korea, Rep.",
        "Lao PDR",
        "Macao SAR, China",
        "Marshall Islands",
        "Myanmar",
        "Mongolia",
        "Northern Mariana Islands",
        "Malaysia",
        "New Caledonia",
        "Nauru",
        "New Zealand",
        "Philippines",
        "Palau",
        "Papua New Guinea",
        "Korea, Dem. People's Rep.",
        "French Polynesia",
        "Singapore",
        "Solomon Islands",
        "Thailand",
        "Timor-Leste",
        "Tonga",
        "Tuvalu",
        "Vietnam",
        "Vanuatu",
        "Samoa"
        ],
    "Europe & Central Asia":[
        "Albania",
        "Andorra",
        "Armenia",
        "Austria",
        "Azerbaijan",
        "Belgium",
        "Bulgaria",
        "Bosnia and Herzegovina",
        "Belarus",
        "Switzerland",
        "Channel Islands",
        "Cyprus",
        "Czech Republic",
        "Germany",
        "Denmark",
        "Spain",
        "Estonia",
        "Finland",
        "France",
        "Faroe Islands",
        "United Kingdom",
        "Georgia",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Croatia",
        "Hungary",
        "Isle of Man",
        "Ireland",
        "Iceland",
        "Italy",
        "Kazakhstan",
        "Kyrgyz Republic",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Latvia",
        "Monaco",
        "Moldova",
        "North Macedonia",
        "Montenegro",
        "Netherlands",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russian Federation",
        "San Marino",
        "Serbia",
        "Slovak Republic",
        "Slovenia",
        "Sweden",
        "Tajikistan",
        "Turkmenistan",
        "Turkey",
        "Ukraine",
        "Uzbekistan",
        "Kosovo"
        ],
    "Latin America & Caribbean":[
        "Aruba",
        "Argentina",
        "Antigua and Barbuda",
        "Bahamas, The",
        "Belize",
        "Bolivia",
        "Brazil",
        "Barbados",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Cuba",
        "Curacao",
        "Cayman Islands",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Grenada",
        "Guatemala",
        "Guyana",
        "Honduras",
        "Haiti",
        "Jamaica",
        "St. Kitts and Nevis",
        "St. Lucia",
        "St. Martin (French part)",
        "Mexico",
        "Nicaragua",
        "Panama",
        "Peru",
        "Puerto Rico",
        "Paraguay",
        "El Salvador",
        "Suriname",
        "Sint Maarten (Dutch part)",
        "Turks and Caicos Islands",
        "Trinidad and Tobago",
        "Uruguay",
        "St. Vincent and the Grenadines",
        "Venezuela, RB",
        "British Virgin Islands",
        "Virgin Islands (U.S.)"
        ],
    "Middle East & North Africa":[
        "United Arab Emirates",
        "Bahrain",
        "Djibouti",
        "Algeria",
        "Egypt, Arab Rep.",
        "Iran, Islamic Rep.",
        "Iraq",
        "Israel",
        "Jordan",
        "Kuwait",
        "Lebanon",
        "Libya",
        "Morocco",
        "Malta",
        "Oman",
        "West Bank and Gaza",
        "Qatar",
        "Saudi Arabia",
        "Syrian Arab Republic",
        "Tunisia",
        "Yemen, Rep."
        ],
    "North America":[
        "Bermuda",
        "Canada",
        "United States"
        ],
    "South Asia":[
        "Afghanistan",
        "Bangladesh",
        "Bhutan",
        "India",
        "Sri Lanka",
        "Maldives",
        "Nepal",
        "Pakistan"
        ],
    "Sub-Saharan Africa":[
        "Angola",
        "Burundi",
        "Benin",
        "Burkina Faso",
        "Botswana",
        "Central African Republic",
        "Cote d'Ivoire",
        "Cameroon",
        "Congo, Dem. Rep.",
        "Congo, Rep.",
        "Comoros",
        "Cabo Verde",
        "Eritrea",
        "Ethiopia",
        "Gabon",
        "Ghana",
        "Guinea",
        "Gambia, The",
        "Guinea-Bissau",
        "Equatorial Guinea",
        "Kenya",
        "Liberia",
        "Lesotho",
        "Madagascar",
        "Mali",
        "Mozambique",
        "Mauritania",
        "Mauritius",
        "Malawi",
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "Sudan",
        "Senegal",
        "Sierra Leone",
        "Somalia",
        "South Sudan",
        "Sao Tome and Principe",
        "Eswatini",
        "Seychelles",
        "Chad",
        "Togo",
        "Tanzania",
        "Uganda",
        "South Africa",
        "Zambia",
        "Zimbabwe"]
};

var all_countries_3_to_2 = {
        "AFG":"AF",
        "ALA":"AX",
        "ALB":"AL",
        "DZA":"DZ",
        "ASM":"AS",
        "AND":"AD",
        "AGO":"AO",
        "AIA":"AI",
        "ATA":"AQ",
        "ATG":"AG",
        "ARG":"AR",
        "ARM":"AM",
        "ABW":"AW",
        "AUS":"AU",
        "AUT":"AT",
        "AZE":"AZ",
        "BHS":"BS",
        "BHR":"BH",
        "BGD":"BD",
        "BRB":"BB",
        "BLR":"BY",
        "BEL":"BE",
        "BLZ":"BZ",
        "BEN":"BJ",
        "BMU":"BM",
        "BTN":"BT",
        "BOL":"BO",
        "BES":"BQ",
        "BIH":"BA",
        "BWA":"BW",
        "BVT":"BV",
        "BRA":"BR",
        "IOT":"IO",
        "VGB":"VG",
        "BRN":"BN",
        "BGR":"BG",
        "BFA":"BF",
        "BDI":"BI",
        "CPV":"CV",
        "KHM":"KH",
        "CMR":"CM",
        "CAN":"CA",
        "CYM":"KY",
        "CAF":"CF",
        "TCD":"TD",
        "CHL":"CL",
        "CHN":"CN",
        "HKG":"HK",
        "MAC":"MO",
        "CXR":"CX",
        "CCK":"CC",
        "COL":"CO",
        "COM":"KM",
        "COG":"CG",
        "COK":"CK",
        "CRI":"CR",
        "HRV":"HR",
        "CUB":"CU",
        "CUW":"CW",
        "CYP":"CY",
        "CZE":"CZ",
        "CIV":"CI",
        "PRK":"KP",
        "COD":"CD",
        "DNK":"DK",
        "DJI":"DJ",
        "DMA":"DM",
        "DOM":"DO",
        "ECU":"EC",
        "EGY":"EG",
        "SLV":"SV",
        "GNQ":"GQ",
        "ERI":"ER",
        "EST":"EE",
        "SWZ":"SZ",
        "ETH":"ET",
        "FLK":"FK",
        "FRO":"FO",
        "FJI":"FJ",
        "FIN":"FI",
        "FRA":"FR",
        "GUF":"GF",
        "PYF":"PF",
        "ATF":"TF",
        "GAB":"GA",
        "GMB":"GM",
        "GEO":"GE",
        "DEU":"DE",
        "GHA":"GH",
        "GIB":"GI",
        "GRC":"GR",
        "GRL":"GL",
        "GRD":"GD",
        "GLP":"GP",
        "GUM":"GU",
        "GTM":"GT",
        "GGY":"GG",
        "GIN":"GN",
        "GNB":"GW",
        "GUY":"GY",
        "HTI":"HT",
        "HMD":"HM",
        "VAT":"VA",
        "HND":"HN",
        "HUN":"HU",
        "ISL":"IS",
        "IND":"IN",
        "IDN":"ID",
        "IRN":"IR",
        "IRQ":"IQ",
        "IRL":"IE",
        "IMN":"IM",
        "ISR":"IL",
        "ITA":"IT",
        "JAM":"JM",
        "JPN":"JP",
        "JEY":"JE",
        "JOR":"JO",
        "KAZ":"KZ",
        "KEN":"KE",
        "KIR":"KI",
        "KWT":"KW",
        "KGZ":"KG",
        "LAO":"LA",
        "LVA":"LV",
        "LBN":"LB",
        "LSO":"LS",
        "LBR":"LR",
        "LBY":"LY",
        "LIE":"LI",
        "LTU":"LT",
        "LUX":"LU",
        "MDG":"MG",
        "MWI":"MW",
        "MYS":"MY",
        "MDV":"MV",
        "MLI":"ML",
        "MLT":"MT",
        "MHL":"MH",
        "MTQ":"MQ",
        "MRT":"MR",
        "MUS":"MU",
        "MYT":"YT",
        "MEX":"MX",
        "FSM":"FM",
        "MCO":"MC",
        "MNG":"MN",
        "MNE":"ME",
        "MSR":"MS",
        "MAR":"MA",
        "MOZ":"MZ",
        "MMR":"MM",
        "NAM":"NA",
        "NRU":"NR",
        "NPL":"NP",
        "NLD":"NL",
        "NCL":"NC",
        "NZL":"NZ",
        "NIC":"NI",
        "NER":"NE",
        "NGA":"NG",
        "NIU":"NU",
        "NFK":"NF",
        "MNP":"MP",
        "NOR":"NO",
        "OMN":"OM",
        "PAK":"PK",
        "PLW":"PW",
        "PAN":"PA",
        "PNG":"PG",
        "PRY":"PY",
        "PER":"PE",
        "PHL":"PH",
        "PCN":"PN",
        "POL":"PL",
        "PRT":"PT",
        "PRI":"PR",
        "QAT":"QA",
        "KOR":"KR",
        "MDA":"MD",
        "ROU":"RO",
        "RUS":"RU",
        "RWA":"RW",
        "REU":"RE",
        "BLM":"BL",
        "SHN":"SH",
        "KNA":"KN",
        "LCA":"LC",
        "MAF":"MF",
        "SPM":"PM",
        "VCT":"VC",
        "WSM":"WS",
        "SMR":"SM",
        "STP":"ST",
        "SAU":"SA",
        "SEN":"SN",
        "SRB":"RS",
        "SYC":"SC",
        "SLE":"SL",
        "SGP":"SG",
        "SXM":"SX",
        "SVK":"SK",
        "SVN":"SI",
        "SLB":"SB",
        "SOM":"SO",
        "ZAF":"ZA",
        "SGS":"GS",
        "SSD":"SS",
        "ESP":"ES",
        "LKA":"LK",
        "PSE":"PS",
        "SDN":"SD",
        "SUR":"SR",
        "SJM":"SJ",
        "SWE":"SE",
        "CHE":"CH",
        "SYR":"SY",
        "TJK":"TJ",
        "THA":"TH",
        "MKD":"MK",
        "TLS":"TL",
        "TGO":"TG",
        "TKL":"TK",
        "TON":"TO",
        "TTO":"TT",
        "TUN":"TN",
        "TUR":"TR",
        "TKM":"TM",
        "TCA":"TC",
        "TUV":"TV",
        "UGA":"UG",
        "UKR":"UA",
        "ARE":"AE",
        "GBR":"GB",
        "TZA":"TZ",
        "UMI":"UM",
        "VIR":"VI",
        "USA":"US",
        "URY":"UY",
        "UZB":"UZ",
        "VUT":"VU",
        "VEN":"VE",
        "VNM":"VN",
        "WLF":"WF",
        "ESH":"EH",
        "YEM":"YE",
        "ZMB":"ZM",
        "ZWE":"ZW"
};

// The color: code sets the color of the individual dat. In this case makes the surveyed ones red
var all_cities_arr = [
    { name: "Jhenaidah",country_code:"BGD", lat:23.545, lon:89.1726, completed:1, color: "red"},
    { name: "Khulna",country_code:"BGD", lat:22.8456, lon:89.5403, completed:1, color: "red"},
    { name: "Kushtia",country_code:"BGD", lat:23.8907, lon:89.1099, completed:1, color: "red"},
    { name: "Accra",country_code:"GHA", lat:5.6037, lon:-0.187, completed:1, color: "red"},
    { name: "Dakar",country_code:"SEN", lat:14.7167, lon:-17.4677, completed:1, color: "red"},
    { name: "Chattogram",country_code:"BGD", lat:22.3569, lon:91.7832, completed:0},
    { name: "Rangpur",country_code:"BGD", lat:25.7439, lon:89.2752, completed:0},
    { name: "Kumasi",country_code:"GHA", lat:6.6666, lon:-1.6163, completed:0},
    { name: "Kisumu",country_code:"KEN", lat:-0.0917, lon:34.768, completed:0},
    { name: "Nairobi",country_code:"KEN", lat:-1.2921, lon:36.8219, completed:0},
    { name: "Nakuru",country_code:"KEN", lat:-0.3031, lon:36.08, completed:0},
    { name: "Maputo",country_code:"MOZ", lat:-25.9692, lon:32.5732, completed:0},
    { name: "Cape Town",country_code:"ZAF", lat:-33.9249, lon:18.4241, completed:0},
    { name: "Johannesburg",country_code:"ZAF", lat:-26.2041, lon:28.0473, completed:0},
    { name: "Colombo",country_code:"LKA", lat:6.9271, lon:79.8612, completed:0},
    { name: "Kampala",country_code:"UGA", lat:0.3476, lon:32.5825, completed:0},
    { name: "Lusaka",country_code:"ZMB", lat:-15.3875, lon:28.3228, completed:0}

];
